# Generated by Django 2.0.4 on 2018-05-13 13:37

from django.db import migrations


def add_subjects(apps, schema_editor):
    Subject = apps.get_model('app', 'Subject')
    Subject.objects.create(name="FMaths", verbose_name="Further Maths", colour="DB995A").save()
    Subject.objects.create(name="Phys", verbose_name="Physics", colour="CC4F4F").save()
    Subject.objects.create(name="CompSci", verbose_name="Computer Science", colour="2D48B5").save()
    Subject.objects.create(name="Results Day", verbose_name="Results Day", colour="757575").save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_subjects),
    ]
