# Generated by Django 2.0.4 on 2018-05-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180513_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
    ]
