# Generated by Django 2.0.5 on 2018-05-20 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_add_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
    ]
