# Generated by Django 2.0.5 on 2018-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180525_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='max_score',
        ),
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=75),
            preserve_default=False,
        ),
    ]
